url: https://cloudpower97.github.io
baseurl: /

# Site settings
title: The Byte-sized
email: claudio.cortese@thebytesized.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ciro Carandente
  pic: ciro_carandente
  position: Founder & CEO
  description: With extensive experience in software development, gained in prestigious environments such as Luxottica and the Italian Red Cross, he demonstrates remarkable ability in leading teams toward important goals, utilizing a wide range of technologies. He is capable of independently managing his/her workload, ensuring the respect of deadlines and objectives, and communicates effectively with clients and users. His/Her teamwork skills, developed both in academic and professional settings, make him/her a reliable and highly competent professional.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ciro-carandente/
    - title: github
      url: https://github.com/codakkk

- name: Claudio Cortese
  pic: claudio_cortese
  position: Founder & CTO
  description: Extensive experience in software development at prestigious companies such as Luxottica, Namirial, and the Italian Red Cross, he excels in leading teams to success while working with diverse technology stacks. He demonstrates autonomy in work organization, meeting deadlines and objectives, and communicates clearly with clients and users. His experience in teamwork, both academic and professional, distinguishes him/her as a reliable and competent professional.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/claudio-cortese/
    - title: github
      url: https://github.com/CloudPower97
    - title: stack-overflow
      url: https://stackoverflow.com/users/5767099/claudio-cortese

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Via Ponti Rossi 259
  - line: Napoli, NA 80141

# Build settings
markdown: kramdown
permalink: pretty