url: https://y7kim.github.io
baseurl: /

# Site settings
title: The Byte-sized
email: claudio.cortese@thebytesized.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ciro Carandente
  pic: ciro_carandente
  position: Founder & CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ciro-carandente/
    - title: github
      url: #

- name: Claudio Cortese
  pic: claudio_cortese
  position: Founder & CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/claudio-cortese/
    - title: github
      url: https://github.com/CloudPower97
    - title: stack-overflow
      url: https://stackoverflow.com/users/5767099/claudio-cortese

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Via Ponti Rossi 259
  - line: Napoli, NA 80141

# Build settings
markdown: kramdown
permalink: pretty